### ISSUE TITLE
Add alexa to a module

### ISSUE THREAD

**Issue by Porkiddo** [sakirtemel/MMM-alexa#2]
Hi, two question for you. I'm just starting to code and already installed the MM2 and 'stand alone' alexa. Can you exemplify how for exemple we hide or show the hello world module with the alexa module?
Does the alexa module still have all the skills and capabilities off the 'stand alone'? 

Thanks

**Comment by sakirtemel** [comment]
I don't think that you can use this module inside of a module. You can create hello world module which listens this module's events (https://github.com/sakirtemel/MMM-alexa#events), or hello world module can emit an event for this module.

Alexa returns speech messages in audio format, so for now there's no way to use alexa as speech to text. So, this module will only listen and return the answers from the speakers with using Alexa platform.

Soon I'm planning to have another module to be combined with this module, and there you can have this options like hiding/showing the modules. When I'm done with that I'll update the readme in here.

**Comment by Porkiddo** [comment]
Brilliant, looking forward to that. Thanks for the answer
