### ISSUE TITLE
Initial ID?

### ISSUE THREAD

**Issue by caractuas** [sakirtemel/MMM-alexa#8]
I have tried installing this module, and after coping my client ID and secret ID I found the initial ID. What is this? Where can I find it? Thanks

**Comment by sakirtemel** [comment]
@caractuas you mean initialCode?

https://github.com/sakirtemel/MMM-alexa#1-adding-magicmirror-to-amazon-avs-service

**Comment by sakirtemel** [comment]
@caractuas I assume that it was about initial code, closing, please re open if that wasn't the case
